[[redirects]]
  from = "/findplacefromtext"
  to = "https://maps.googleapis.com/maps/api/place/findplacefromtext"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"